kind: pipeline
name: default

steps:
- name: build
  image: cbrgm/drone-hugo:latest
  settings:
    hugo_version: 0.55
    pull: always
    url: https://chromic.org

- name: deploy
  image: appleboy/drone-scp
  settings:
    target: /usr/share/webapps/chromic.org
    source: public/*
    rm: true
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

