kind: pipeline
name: default

steps:
- name: build
  image: klakegg/hugo:0.59.1-ext-alpine
  commands:
    - hugo-official
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: deploy
  image: appleboy/drone-scp
  settings:
    target: /usr/share/webapps/chromic.org
    source: public/*
    rm: true
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

