scss_files: "_sass/chimo/*.scss"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    width: 4
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  ImportantRule:
    enabled: false
  QualifyingElement:
    enabled: false
  ColorVariable:
    enabled: false
  NestingDepth:
    enabled: false
  IdSelector:
    enabled: false
  DuplicateProperty:
    enabled: false

