# Site wide configuration

url: //chromic.org
title: Chromic
locale: en_CA
description: Stuff and Things.
logo: site-logo.png
timezone: America/Toronto

# Jekyll configuration

destination: ../public_html
excerpt_separator: <!-- more -->
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".well-known"]
exclude: ["bin", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Chimo
  avatar: bio-photo.png
  email: chimo@chromic.org
  twitter: chim0
  github: chimo

defaults:
  -
    scope:
      path: ""
    values:
      share: true
      comments: true
  -
    scope:
      path: "blog"
      #type: "posts"
    values:
      layout: "post"
