languageCode = "en-ca"
title = "chromic"
baseurl = "https://chromic.org"
theme = "so-simple"

pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

